// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPPQhnHLbaNvBieQ49Thasnr5l-hhCsZs',
    appId: '1:807427119321:android:a557979e1e6dd0bdcf86c8',
    messagingSenderId: '807427119321',
    projectId: 'exam4-4ff56',
    databaseURL: 'https://exam4-4ff56-default-rtdb.firebaseio.com',
    storageBucket: 'exam4-4ff56.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7wIaOwXt_mgEu6wZVvM30mE4pQnOMYCM',
    appId: '1:807427119321:ios:565a386b05753d2bcf86c8',
    messagingSenderId: '807427119321',
    projectId: 'exam4-4ff56',
    databaseURL: 'https://exam4-4ff56-default-rtdb.firebaseio.com',
    storageBucket: 'exam4-4ff56.firebasestorage.app',
    iosClientId: '807427119321-2uufvrmpgegev4o6d8g21o22504d310q.apps.googleusercontent.com',
    iosBundleId: 'com.example.imtihon4',
  );
}
